#!/usr/bin/env texlua

---@diagnostic disable: lowercase-global
module = "cvd"

sourcefiledir = "src"
sourcefiles = {"*.dtx", "*.ins", "*.lua"}
unpackfiles = {"*.ins"}
installfiles = {"*.sty", "*.lua"}
-- The .lua file needs to be treated as both source and installable
-- Since it's not generated by docstrip, add it to unpacksuppfiles
unpacksuppfiles = {"*.lua"}

docfiledir = "docs/_site"
typesetfiles = { "*.tex" }
docfiles = { "cvd.pdf" }
textfiles = { "*.md", "LICENSE" }
checkengines = { "pdftex" }
checksuppfiles = { "*.tex" }

packtdszip = false

maxprintline = 9999

uploadconfig = {
	pkg = "cvd",
	version = "0.1.0",
	author = "Johan Larsson",
	uploader = "Johan Larsson",
	license = "mit",
	summary = "CVD correction",
	description = "Simulate and correct for color vision deficiencies in images.",
	-- ctanPath = "/macros/latex/contrib/beamer-contrib/themes/moloch",
	repository = "https://github.com/jolars/cvd",
	bugtracker = "https://github.com/jolars/cvd",
	topic = "colour vision,color blindness,image processing,latex",
	announcement_file = "ctan_announcement.txt",
}
